name: "Container Structure Test Action"
description: "Run Container Tests"
author: "Nexient DevSecOps"

inputs:
  image:
    description: "Image:Tag to Test"
  config:
    description: "Path to test file to run (e.g.; ./test.yaml)"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - test
    - --image
    - ${{ inputs.image }}
    - --config
    - ${{ inputs.config }}
