name: Build, Test, and Publish Alpine Image

on:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  push_to_registry:
    name: Push Alpine Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nexientdevops/container-template
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=sha
      - name: Build Alpine Based Image
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfiles/Alpine/3
          push: false
          tags: nexientdevops/container-template:test
      - name: Run Container Tests
        uses: ./.github/actions/container-structure-test
        with:
          image: nexientdevops/container-template:test
          config: test.yaml
      - name: Push Alpine Based Image
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfiles/Alpine/3
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}